document.write('<table width="100%" summary="footer"  border="0" cellspacing="0" cellpadding="0">');
document.write('<tr>');
document.write('<td colspan="2" bgcolor="#1578BB"><img src="/error/img/space.gif" alt="" width="1" height="3" border="0"></td>');
document.write('</tr>');
document.write('<tr>');
document.write('<td colspan="2"><img src="/error/img/space.gif" alt="" width="1" height="5" border="0"></td>');
document.write('</tr>');
document.write('<tr>');
document.write('<td>');
document.write('<table border="0" cellspacing="0" cellpadding="0">');
document.write('<tr>');
document.write('<td><a href="http://www.benesse.co.jp/privacy/" target="_blank"><img src="/error/img/btn_personal.gif" alt="個人情報保護への取り組みについて" width="167" height="15" border="0"></a></td>');
document.write('<td><a href="http://benesse.jp/index.html" target="_blank"><img src="/error/img/btn_education.gif" alt="Benesse 教育情報サイト" width="125" height="15" border="0"></a></td>');
document.write('</tr>');
document.write('</table></td>');
document.write('<td align="right" nowrap><img src="/error/img/copyright_2006.gif" alt="Benesse Corporation. All rights reserved." width="251" height="15" border="0"></td>');
document.write('</tr>');
document.write('<tr>');
document.write('<td colspan="2"><img src="/error/img/space.gif" alt="" width="1" height="5" border="0"></td>');
document.write('</tr>');
document.write('<tr>');
document.write('<td colspan="2" bgcolor="#CCD6E0"><img src="/error/img/space.gif" alt="" width="1" height="1" border="0"></td>');
document.write('</tr>');
document.write('</table>');
