document.write('<table width="100%"  border="0" cellspacing="0" cellpadding="0" summary="header">');
document.write('<tr>');
document.write('<td width="323" rowspan="7"><table width="323" border="0" cellspacing="0" cellpadding="0">');
document.write('<tr>');
document.write('<td rowspan="3"><a href="http://www.benesse.co.jp"><img src="/error/img/top_benesse.gif" alt="Benesse" width="124" height="43" border="0"></a></td>');
document.write('<td colspan="2"><img src="/error/img/space.gif" alt="" width="1" height="18" border="0"></td>');
document.write('</tr>');
document.write('<tr>');
document.write('<td><img src="/error/img/top_message.gif" alt="一人ひとりの「よく生きる」のために" width="185" height="11" border="0"></td>');
document.write('<td><img src="/error/img/space.gif" alt="" width="14" height="1" border="0"></td>');
document.write('</tr>');
document.write('<tr>');
document.write('<td colspan="2"><img src="/error/img/space.gif" alt="" width="1" height="15" border="0"></td>');
document.write('</tr>');
document.write('</table></td>');
document.write('<td><img src="/error/img/space.gif" alt="" width="1" height="5" border="0"></td>');
document.write('</tr>');
document.write('<tr>');
document.write('<td align="right"><a href="http://www.benesse.co.jp/map/index.html"><img src="/error/img/btn_sitemap.gif" alt="ベネッセ サイトマップ" width="124" height="13" border="0"></a></td>');
document.write('</tr>');
document.write('<tr>');
document.write('<td align="right"><img src="/error/img/space.gif" alt="" width="1" height="3" border="0"></td>');
document.write('</tr>');
document.write('<tr>');
document.write('<td align="right" bgcolor="#CCD6E0"><img src="/error/img/space.gif" alt="" width="1" height="1" border="0"></td>');
document.write('</tr>');
document.write('<tr>');
document.write('<td align="right"><img src="/error/img/space.gif" alt="" width="1" height="4" border="0"></td>');
document.write('</tr>');
document.write('<tr>');
document.write('<td align="right"><a href="http://www.benesse.co.jp"><img src="/error/img/btn_top.gif" alt="ベネッセ トップ" width="101" height="13" border="0"></a><a href="http://www.benesse.co.jp/kyouiku/index.html"><img src="/error/img/btn_ed_top.gif" alt="教育トップ" width="74" height="13" border="0"></a></td>');
document.write('</tr>');
document.write('<tr>');
document.write('<td><img src="/error/img/space.gif" alt="" width="1" height="4" border="0"></td>');
document.write('</tr>');
document.write('<tr>');
document.write('<td colspan="2" background="/error/img/bg_head.gif"><img src="/error/img/space.gif" alt="" width="1" height="9"></td>');
document.write('</tr>');
document.write('</table>');
